// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskDistributionSystem.Models;

namespace TaskDistributionSystem.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250810124549_SeedPersonel")]
    partial class SeedPersonel
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32");

            modelBuilder.Entity("TaskDistributionSystem.Models.Gorev", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Aciklama")
                        .HasColumnType("TEXT")
                        .HasMaxLength(1000);

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(100);

                    b.Property<int>("IslemId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PersonelId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IslemId");

                    b.HasIndex("PersonelId");

                    b.ToTable("Gorevler");
                });

            modelBuilder.Entity("TaskDistributionSystem.Models.Islem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(80);

                    b.Property<int>("Zorluk")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Islemler");
                });

            modelBuilder.Entity("TaskDistributionSystem.Models.Personel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Rol")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Personeller");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ad = "Ali",
                            Rol = 0,
                            Soyad = "Yılmaz"
                        },
                        new
                        {
                            Id = 2,
                            Ad = "Ayşe",
                            Rol = 0,
                            Soyad = "Demir"
                        },
                        new
                        {
                            Id = 3,
                            Ad = "Mehmet",
                            Rol = 0,
                            Soyad = "Kaya"
                        },
                        new
                        {
                            Id = 4,
                            Ad = "Elif",
                            Rol = 0,
                            Soyad = "Çetin"
                        },
                        new
                        {
                            Id = 5,
                            Ad = "Can",
                            Rol = 0,
                            Soyad = "Aksoy"
                        },
                        new
                        {
                            Id = 6,
                            Ad = "Zeynep",
                            Rol = 0,
                            Soyad = "Şahin"
                        },
                        new
                        {
                            Id = 7,
                            Ad = "Burak",
                            Rol = 0,
                            Soyad = "Koç"
                        },
                        new
                        {
                            Id = 8,
                            Ad = "Ece",
                            Rol = 0,
                            Soyad = "Aydın"
                        });
                });

            modelBuilder.Entity("TaskDistributionSystem.Models.Gorev", b =>
                {
                    b.HasOne("TaskDistributionSystem.Models.Islem", "Islem")
                        .WithMany("Gorevler")
                        .HasForeignKey("IslemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaskDistributionSystem.Models.Personel", "Personel")
                        .WithMany()
                        .HasForeignKey("PersonelId");
                });
#pragma warning restore 612, 618
        }
    }
}
